name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install -r requirements.txt
      - name: Test with pytest
        run: python3 -m  pytest --doctest-modules --cov=src --junitxml=report-${{ matrix.python-version }}/test-results.xml --cov-report=xml:report-${{ matrix.python-version }}/coverage.xml --cov-report=html:report-${{ matrix.python-version }}/htmlcov --cov-report term:skip-covered
      - name: Upload pytest test results
        uses: actions/upload-artifact@master
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: report-${{ matrix.python-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
